export const employeeData = [
  {
    name: "Anita",
    department: "IT Services",
    assigned: 90,
    ongoing: 90,
    overdue: 90,
    completed: 90,
  },
  {
    name: "Anita",
    department: "IT Services",
    assigned: 90,
    ongoing: 90,
    overdue: 90,
    completed: 90,
  },
  {
    name: "Anita",
    department: "IT Services",
    assigned: 90,
    ongoing: 90,
    overdue: 90,
    completed: 90,
  },
  {
    name: "Anita",
    department: "IT Services",
    assigned: 90,
    ongoing: 90,
    overdue: 90,
    completed: 90,
  },
];

export const employeeTabs = [
  { key: 0, label: "Tasks", count: 10, color: "bg-green-500" },
  { key: 1, label: "Issues", count: 10, color: "bg-orange-500" },
  { key: 2, label: "Workflows", count: 10, color: "bg-purple-500" },
];

export const statsCards = [
  {
    title: "22 AI Review",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    iconColor: "text-green-600",
    icon: "🤖",
    details: "Manually Approve 2 • Completed 10 • Rejected by AI 10",
  },
  {
    title: "22 Tasks",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    iconColor: "text-blue-600",
    icon: "📋",
    details: "Ongoing 10 • Overdue 2 • Completed 10 • Scheduled 0",
  },
  {
    title: "22 Issues",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    iconColor: "text-orange-600",
    icon: "⚠️",
    details: "Ignored 2 • Resolved 10 • Open 10",
  },
  {
    title: "20 Forms",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
    iconColor: "text-purple-600",
    icon: "📝",
    details: "Open Responses 0 • Sl...",
  },
];

export const workTabs = [
  { key: 0, label: "Tasks", count: 10, color: "bg-green-500" },
  { key: 1, label: "Issues", count: 10, color: "bg-orange-500" },
  { key: 2, label: "Forms", count: 10, color: "bg-purple-500" },
];

export const workItems = [
  {
    id: "#3789",
    title: "How to Manage Stock",
    date: "22 June, 2024",
    time: "11:00 am",
    status: "Ongoing",
    category: "Inventory",
    comments: 14,
    assignee: "A",
  },
  {
    id: "#3789",
    title: "How to Manage Stock",
    date: "3 April, 2025",
    time: "11:00 am",
    status: "Ongoing",
    category: "Inventory",
    comments: 14,
    assignee: "A",
  },
  {
    id: "#7182",
    title: "Tracking Daily Earnings",
    date: "12 October, 2024",
    time: "11:00 am",
    status: "Ongoing",
    category: "Inventory",
    comments: 18,
    assignee: "A",
  },
  {
    id: "#6047",
    title: "Tool for Managing Reservations",
    date: "15 March, 2024",
    time: "2:00 pm",
    status: "Ongoing",
    category: "Reservations",
    comments: 17,
    assignee: "A",
  },
  {
    id: "#6047",
    title: "Tool for Managing Reservations",
    date: "20 May, 2024",
    time: "10:30 am",
    status: "Ongoing",
    category: "Reservations",
    comments: 17,
    assignee: "A",
  },
  {
    id: "#4820",
    title: "Coordinating Employee Shifts",
    date: "8 July, 2024",
    time: "3:15 pm",
    status: "Ongoing",
    category: "HR",
    comments: 15,
    assignee: "A",
  },
  {
    id: "#6047",
    title: "Tool for Managing Reservations",
    date: "20 May, 2024",
    time: "10:30 am",
    status: "Ongoing",
    category: "Reservations",
    comments: 17,
    assignee: "A",
  },
  {
    id: "#4820",
    title: "Coordinating Employee Shifts",
    date: "8 July, 2024",
    time: "3:15 pm",
    status: "Ongoing",
    category: "HR",
    comments: 15,
    assignee: "A",
  },
  {
    id: "#6047",
    title: "Tool for Managing Reservations",
    date: "20 May, 2024",
    time: "10:30 am",
    status: "Ongoing",
    category: "Reservations",
    comments: 17,
    assignee: "A",
  },
  {
    id: "#4820",
    title: "Coordinating Employee Shifts",
    date: "8 July, 2024",
    time: "3:15 pm",
    status: "Ongoing",
    category: "HR",
    comments: 15,
    assignee: "A",
  },
  {
    id: "#6047",
    title: "Tool for Managing Reservations",
    date: "20 May, 2024",
    time: "10:30 am",
    status: "Ongoing",
    category: "Reservations",
    comments: 17,
    assignee: "A",
  },
  {
    id: "#4820",
    title: "Coordinating Employee Shifts",
    date: "8 July, 2024",
    time: "3:15 pm",
    status: "Ongoing",
    category: "HR",
    comments: 15,
    assignee: "A",
  },
  {
    id: "#6047",
    title: "Tool for Managing Reservations",
    date: "20 May, 2024",
    time: "10:30 am",
    status: "Ongoing",
    category: "Reservations",
    comments: 17,
    assignee: "A",
  },
  {
    id: "#4820",
    title: "Coordinating Employee Shifts",
    date: "8 July, 2024",
    time: "3:15 pm",
    status: "Ongoing",
    category: "HR",
    comments: 15,
    assignee: "A",
  },
];

export const workflowsData = [
  {
    id: 1,
    title: "Stock Control Strategies",
    responses: 47,
    tasks: 22,
    status: "active",
  },
  {
    id: 2,
    title: "How to Handle Inventory",
    responses: 23,
    tasks: 15,
    status: "active",
  },
  {
    id: 3,
    title: "Inventory Management Tips",
    responses: 56,
    tasks: 30,
    status: "active",
  },
  {
    id: 4,
    title: "Managing Your Stock Effectively",
    responses: 89,
    tasks: 5,
    status: "active",
  },
];

export const notesData = [
  {
    id: 1,
    title: "Make shift & assign",
    description:
      "Assign individuals to specific shifts based on availability and role requirements",
    completed: false,
  },
  {
    id: 2,
    title: "Menu correction",
    description:
      "Update the menu to show the dishes and their ingredients clearly. Point out any new cooking methods or dietary options.",
    completed: true,
  },
];
export const tasks = [
  {
    id: 1,
    name: "Menu Planning",
    assignedTo: "Ajay",
    status: "overdue",
    dueDate: "12-07-2024",
  },
  {
    id: 2,
    name: "Staff Scheduling",
    assignedTo: "Niraj",
    status: "overdue",
    dueDate: "01-08-2023",
  },
  {
    id: 3,
    name: "Inventory management",
    assignedTo: "Vijay",
    status: "overdue",
    dueDate: "02-09-2022",
  },
  {
    id: 4,
    name: "Customer Feedback Anal...",
    assignedTo: "Arvind",
    status: "overdue",
    dueDate: "11-06-2025",
  },
];

export const departmentAllocationData = [
  { department: "Dept 1", tasks: 10, overdueTasks: 5, total: 15 },
  { department: "Dept 2", tasks: 30, overdueTasks: 6, total: 36 },
  { department: "Dept 3", tasks: 38, overdueTasks: 20, total: 58 },
  { department: "Dept 4", tasks: 73, overdueTasks: 20, total: 93 },
  { department: "Dept 5", tasks: 72, overdueTasks: 23, total: 95 },
];
